name: UPUer
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  curved_navigation_bar: ^1.0.3
  curved_labeled_navigation_bar: ^2.0.2
  fluttertoast: ^8.2.1
  flutter_svg: ^2.0.1
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  dio: ^5.0.1
  intl: ^0.17.0
  carousel_slider: ^4.2.1
  qr_flutter: ^4.0.0
  pin_code_fields: ^7.4.0
  get_it: ^7.2.0
  flutter_slidable: ^3.0.0
  url_launcher: ^6.1.10
  image_picker: ^0.8.6+4
  cached_network_image: ^3.2.3
  qr_code_scanner: ^1.0.1
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.1
  get: ^4.6.5
  dropdown_button2: ^2.1.2
  webview_flutter: ^3.0.0
  firebase_storage: ^11.2.2
  fl_chart: ^0.62.0
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    # - .env.prod
    # - .env.dev
    - assets/icons/
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Italic.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
